on:
  push:
    branches:
    - master
  workflow_dispatch:
    branches:
    - master

name: Publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout' 
      uses: actions/checkout@master
      with:
        ref: master

    - uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AzurePublishProfile }}
